# Generated by Django 6.0.4 on 2026-09-03 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONFIRMADA', 'Confirmada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Cancelada'), ('REMARCADA', 'Remarcada')], default='AGENDADA', max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['data', 'horario'],
            },
        ),
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Procedimento',
                'verbose_name_plural': 'Procedimentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField()),
                ('diagnostico', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='CONCLUIDO', max_length=20)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='atendimento', to='DentalTech.agendamento')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Dente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('SAUDAVEL', 'Saudável'), ('CARIE', 'Cárie'), ('RESTAURADO', 'Restaurado'), ('AUSENTE', 'Ausente'), ('EXTRAIDO', 'Extraído'), ('FRATURADO', 'Fraturado'), ('OUTRO', 'Outro')], default='SAUDAVEL', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentes', to='DentalTech.odontograma')),
            ],
            options={
                'verbose_name': 'Dente',
                'verbose_name_plural': 'Dentes',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='odontograma',
            name='paciente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odontograma', to='DentalTech.paciente'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='DentalTech.paciente'),
        ),
        migrations.CreateModel(
            name='AtendimentoProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimentos', to='DentalTech.atendimento')),
                ('dente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedimentos_realizados', to='DentalTech.dente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='DentalTech.procedimento')),
            ],
            options={
                'verbose_name': 'Procedimento Realizado',
                'verbose_name_plural': 'Procedimentos Realizados',
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cro', models.CharField(max_length=20, unique=True, verbose_name='CRO')),
                ('especialidade', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profissional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profissional',
                'verbose_name_plural': 'Profissionais',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='DentalTech.profissional'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='DentalTech.profissional'),
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True)),
                ('medicamentos', models.TextField(blank=True)),
                ('historico_medico', models.TextField(blank=True)),
                ('historico_odontologico', models.TextField(blank=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prontuario', to='DentalTech.paciente')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADMINISTRATIVO', 'Administrativo'), ('CLINICO', 'Clínico')], max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('gerado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Tratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('diagnostico', models.TextField(blank=True)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('dente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamentos', to='DentalTech.dente')),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos', to='DentalTech.odontograma')),
            ],
            options={
                'verbose_name': 'Tratamento',
                'verbose_name_plural': 'Tratamentos',
            },
        ),
        migrations.AddConstraint(
            model_name='dente',
            constraint=models.UniqueConstraint(fields=('odontograma', 'numero'), name='dente_unico_por_odontograma'),
        ),
    ]
