# Generated by Django 6.1.1 on 2026-09-24 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DentalTech', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimentoprocedimento',
            options={'verbose_name': 'Procedimento do Atendimento', 'verbose_name_plural': 'Procedimentos do Atendimento'},
        ),
        migrations.DeleteModel(
            name='Relatorio',
        ),
    ]
